apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: bmysql
  name: bmysql
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: bmysql
status:
  loadBalancer: {}
