apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: brabbitmq
  name: brabbitmq
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: brabbitmq
status:
  loadBalancer: {}
