language: go
dist: xenial
os: linux

go:
  - "1.15"

go_import_path: github.com/letsencrypt/boulder

services:
  - docker

# Only build pushes to the main branch, PRs, and branches beginning with
# `test-`. You should not push branches beginning with `test-` to the
# letsencrypt repository, but this is a convenient way to push branches to your
# own fork of the repository to ensure Travis passes before submitting a PR.
# For instance, you might run:
# git push myremote branchname:test-branchname
branches:
  only:
    - main
    - /^test-.*$/

env:
    # With no options passed: runs lint, unit, and integation
    # l: Adds lint to the list of tests to run
    # u: Adds unit to the list of tests to run
    # d: Run unit tests for a specific directory
    # e: Sets $TRAVIS to true, enabling -race flag for unit tests
    # n: Changes BOULDER_CONFIG_DIR from test/config to test/config-next
    # c: Adds coverage to the list of tests to run
    # i: Adds integration to the list of tests to run
    # s: Adds start (py) to the list of tests to run
    # v: Adds gomod-vendor to the list of tests to run
    # g: Adds generate to the list of tests to run
    # r: Adds rpm to the list of tests to run
    # p: Outputs a list of the available integration tests
    # f: Run only those tests and examples matching the regular expression
    - TESTFLAGS="ligr"
    # Config changes that have landed in main but not yet been applied to
    # production can be made in boulder-config-next.json.
    - TESTFLAGS="in"
    - TESTFLAGS="eu"
    - TESTFLAGS="eun"
    - TESTFLAGS="s"
    # gomod-vendor runs with a separate container because it needs to fetch
    # packages from GitHub et. al., which is incompatible with the DNS server
    # override in the boulder container (used for service discovery).
    - TESTFLAGS="v" CONTAINER="netaccess"
    - TESTFLAGS="c" CONTAINER="netaccess"

jobs:
  fast_finish: true
  allow_failures:
    - env: RUN=(coverage) CONTAINER="netaccess"

install:
  - docker-compose pull

script:
  - >-
    docker-compose run --use-aliases
    -e TRAVIS_BRANCH
    -e TRAVIS_JOB_ID
    -e TRAVIS_PULL_REQUEST
    -e COVERALLS_TOKEN
    ${CONTAINER:-boulder} ./test.sh -${TESTFLAGS}
