version: '2'
services:
    boulder:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            FAKE_DNS: 127.0.0.1
            PKCS11_PROXY_SOCKET: tcp://boulder-hsm:5657
            BOULDER_CONFIG_DIR: test/config
        volumes:
          - .:/go/src/github.com/letsencrypt/boulder
          - /tmp:/tmp
        extra_hosts:
          - le.wtf:127.0.0.1
          - boulder:127.0.0.1
        ports:
          - 4000:4000 # ACME
          - 4001:4001 # ACMEv2
          - 4002:4002 # OCSP
          - 4003:4003 # OCSP
          - 4430:4430 # ACME via HTTPS
          - 4431:4431 # ACMEv2 via HTTPS
          - 4500:4500 # ct-test-srv
          - 6000:6000 # gsb-test-srv
          - 8000:8000 # debug ports
          - 8001:8001
          - 8002:8002
          - 8003:8003
          - 8004:8004
          - 8005:8005
          - 8006:8006
          - 8008:8008
          - 8009:8009
          - 8010:8010
          - 8055:8055 # dns-test-srv updates
          - 9380:9380 # mail-test-srv
          - 9381:9381 # mail-test-srv
        depends_on:
          - bhsm
          - bmysql
    bhsm:
        # To minimize the fetching of various layers this should match
        # the FROM image and tag in boulder/Dockerfile
        image: letsencrypt/boulder-tools:2018-02-15
        environment:
            PKCS11_DAEMON_SOCKET: tcp://0.0.0.0:5657
        command: /usr/local/bin/pkcs11-daemon /usr/lib/softhsm/libsofthsm2.so
        # Allow other containers to use the name `boulder-hsm` to connect
        networks:
            default:
                aliases:
                  - boulder-hsm
    bmysql:
        image: mariadb:10.1
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        command: mysqld --bind-address=0.0.0.0
        logging:
            driver: none
        networks:
            default:
                aliases:
                  - boulder-mysql
    prom:
        image: prom/prometheus:v1.8.2
        ports:
          - 9090:9090
        volumes:
          - ./test/prometheus/:/promconf/
        command: -config.file /promconf/prometheus.yml
        depends_on:
          - boulder
